import type { Metadata } from "next";
import Link from "next/link";

import { SiteFooter } from "@/components/layout/SiteFooter";
import { SiteHeader } from "@/components/layout/SiteHeader";

export const metadata: Metadata = {
  title: "Terms of Use - Be In The Know",
  description: "The terms that apply when you use Be In The Know and Just Ask JO.",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-7">
      <h2 className="text-base font-bold text-[#085041]">{title}</h2>
      <div className="mt-2 space-y-3">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <SiteHeader />
      <main className="mx-auto max-w-3xl px-4 py-10 text-[14px] leading-6 text-gray-700">
        <h1 className="text-2xl font-bold text-[#085041]">Terms of Use</h1>
        <p className="mt-2 text-[12px] text-gray-500">Effective date: July 2026</p>

        <p className="mt-4">
          Welcome to Be In The Know ("the Service"), including our assistant,
          JO. By using the Service - with or without an account - you agree to
          these Terms of Use. If you do not agree, please do not use the
          Service. We wrote these terms in plain language on purpose, because
          that is what this whole project is about.
        </p>

        <Section title="1. The Service is education, not legal advice">
          <p>
            Be In The Know provides general educational information about legal
            rights. It is not a law firm, JO is not a lawyer, and nothing on
            the Service is legal advice about your specific situation. Using
            the Service does not create an attorney-client relationship.
          </p>
          <p>
            Laws differ by state, change over time, and depend on facts we
            cannot know. Before acting on anything you read here, verify it
            with the cited official source and consider talking to a legal aid
            organization or a licensed attorney in your state.
          </p>
        </Section>

        <Section title="2. Answers are generated by AI from reviewed sources">
          <p>
            JO's answers are written by an artificial intelligence model using
            a reviewed library of official statute text and plain-language
            summaries. We design JO to answer only from those sources and to
            show citations - but AI can make mistakes, summaries can simplify,
            and sources can become outdated. The citations exist so you can
            check the official text yourself. Always do that before relying on
            an answer.
          </p>
        </Section>

        <Section title="3. Accounts">
          <p>
            You may use the Service as a guest or create an account with your
            email address. You are responsible for keeping your password
            private and for activity on your account. You must provide accurate
            information and be at least 13 years old to create an account. We
            may set daily limits on questions to keep the Service available to
            everyone.
          </p>
        </Section>

        <Section title="4. Acceptable use">
          <p>
            Do not use the Service to break the law, to attempt to disrupt or
            overload it, to probe or bypass its security or usage limits, to
            scrape it at scale, or to misrepresent its answers as professional
            legal advice to others. We may suspend access that violates these
            terms.
          </p>
        </Section>

        <Section title="5. Third-party links">
          <p>
            Answers and topic pages link to official government sites and
            trusted nonprofit resources. Those sites belong to their owners; we
            are not responsible for their content.
          </p>
        </Section>

        <Section title="6. No warranty">
          <p>
            The Service is provided "as is" and "as available," without
            warranties of any kind, express or implied - including accuracy,
            completeness, currentness, or fitness for a particular purpose. We
            work hard to keep the library current, but we cannot promise that
            every answer reflects the law as it stands today.
          </p>
        </Section>

        <Section title="7. Limitation of liability">
          <p>
            To the fullest extent permitted by law, Be In The Know and its
            creator will not be liable for indirect, incidental, special,
            consequential, or punitive damages, or for decisions made in
            reliance on the Service. Your only remedy for dissatisfaction with
            the Service is to stop using it.
          </p>
        </Section>

        <Section title="8. Changes">
          <p>
            We may update these terms as the Service evolves. When we do, we
            will update the effective date above. Continuing to use the Service
            after a change means you accept the updated terms.
          </p>
        </Section>

        <Section title="9. Contact">
          <p>
            Questions about these terms: joanneliszewski@gmail.com
          </p>
        </Section>

        <p className="mt-8 text-[12px] text-gray-500">
          See also our <Link href="/privacy" className="font-semibold text-[#085041] hover:underline">Privacy Policy</Link>{" "}
          and <Link href="/about" className="font-semibold text-[#085041] hover:underline">About page</Link>.
        </p>
      </main>
      <SiteFooter />
    </div>
  );
}
